// 应用
export const SET_SIDEBAR_OPENKEYS = 'SET_SIDEBAR_OPENKEYS'
export const SET_SIDEBAR_SELECTKEYS = 'SET_SIDEBAR_SELECTKEYS'

// 文章类别
export const GET_POSTS_CATEGORIES = 'GET_POSTS_CATEGORIES'
export const GET_POSTS_CATEGORIES_SUCCEEDED = 'GET_POSTS_CATEGORIES_SUCCEEDED'
export const GET_POSTS_CATEGORIES_COUNT = 'GET_POSTS_CATEGORIES_COUNT'
export const GET_POSTS_CATEGORIES_COUNT_SUCCEEDED = 'GET_POSTS_CATEGORIES_COUNT_SUCCEEDED'
export const ADD_POSTS_CATEGORY = 'ADD_POSTS_CATEGORY'
export const UPDATE_POSTS_CATEGORY = 'UPDATE_POSTS_CATEGORY'
export const DELETE_POSTS_CATEGORY = 'DELETE_POSTS_CATEGORY'

// 文章标签
export const GET_POSTS_TAGS = 'GET_POSTS_TAGS'
export const GET_POSTS_TAGS_SUCCEEDED = 'GET_POSTS_TAGS_SUCCEEDED'
export const GET_POSTS_TAGS_COUNT = 'GET_POSTS_TAGS_COUNT'
export const GET_POSTS_TAGS_COUNT_SUCCEEDED = 'GET_POSTS_TAGS_COUNT_SUCCEEDED'
export const ADD_POSTS_TAG = 'ADD_POSTS_TAG'
export const UPDATE_POSTS_TAG = 'UPDATE_POSTS_TAG'
export const DELETE_POSTS_TAG = 'DELETE_POSTS_TAG'

// 文章管理
export const GET_POSTS = 'GET_POSTS'
export const GET_POSTS_SUCCEEDED = 'GET_POSTS_SUCCEEDED'
export const GET_POSTS_COUNT = 'GET_POSTS_COUNT'
export const GET_POSTS_COUNT_SUCCEEDED = 'GET_POSTS_COUNT_SUCCEEDED'
export const GET_POST_BY_ID = 'GET_POST_BY_ID'
export const GET_POST_SUCCEEDED = 'GET_POST_SUCCEEDED'
export const ADD_POST = 'ADD_POST'
export const UPDATE_POST = 'UPDATE_POST'
export const DELETE_POST = 'DELETE_POST'
// 文章相关，主要用于前端页面
export const GET_POST_BY_SEOURL = 'GET_POST_BY_SEOURL'
export const POSTS_PAGEVIEWING = 'POSTS_PAGEVIEWING'


// 用户管理（管理员）
export const GET_MANAGERS = 'GET_MANAGERS'
export const GET_MANAGERS_SUCCEEDED = 'GET_MANAGERS_SUCCEEDED'
export const GET_MANAGERS_COUNT = 'GET_MANAGERS_COUNT'
export const GET_MANAGERS_COUNT_SUCCEEDED = 'GET_MANAGERS_COUNT_SUCCEEDED'
export const ADD_MANAGER = 'ADD_MANAGER'
export const UPDATE_MANAGER = 'UPDATE_MANAGER'
export const DELETE_MANAGER = 'DELETE_MANAGER'

// 用户登录（管理员）
export const MANAGER_LOGIN = 'MANAGER_LOGIN'
export const MANAGER_LOGOUT = 'MANAGER_LOGOUT'
export const GET_MANAGER_INFO = 'GET_MANAGER_INFO'
export const SET_MANAGER_INFO = 'SET_MANAGER_INFO'
export const SET_MANAGER_TOKEN = 'SET_MANAGER_TOKEN'
export const SET_MANAGER_MENUS = 'SET_MANAGER_MENUS'
export const SET_MANAGER_NICKNAME = 'SET_MANAGER_NICKNAME'
export const SET_MANAGER_AVATARURL = 'SET_MANAGER_AVATARURL'
export const SET_MANAGER_INTRODUCTION = 'SET_MANAGER_INTRODUCTION'
export const SET_MANAGER_TAGS = 'SET_MANAGER_TAGS'
export const UPDATE_MANAGER_INFO = 'UPDATE_MANAGER_INFO'
export const UPDATE_MANAGER_TAGS = 'UPDATE_MANAGER_TAGS'
export const CHANGE_MANAGER_PASSWORD = 'CHANGE_MANAGER_PASSWORD'

// 资源管理
export const GET_RESOURCES = 'GET_RESOURCES'
export const GET_RESOURCES_SUCCEEDED = 'GET_RESOURCES_SUCCEEDED'
export const GET_RESOURCES_COUNT = 'GET_RESOURCES_COUNT'
export const GET_RESOURCES_COUNT_SUCCEEDED = 'GET_RESOURCES_COUNT_SUCCEEDED'
export const ADD_RESOURCE = 'ADD_RESOURCE'
export const UPDATE_RESOURCE = 'UPDATE_RESOURCE'
export const DELETE_RESOURCE = 'DELETE_RESOURCE'

// 角色权限
export const GET_ROLES = 'GET_ROLES'
export const GET_ROLES_SUCCEEDED = 'GET_ROLES_SUCCEEDED'
export const GET_ROLES_COUNT = 'GET_ROLES_COUNT'
export const GET_ROLES_COUNT_SUCCEEDED = 'GET_ROLES_COUNT_SUCCEEDED'
export const ADD_ROLE = 'ADD_ROLE'
export const UPDATE_ROLE = 'UPDATE_ROLE'
export const DELETE_ROLE = 'DELETE_ROLE'
